### ISSUE TITLE
does not convert

### ISSUE THREAD

**Issue by riox6l** [AmpedWasTaken/Fivem-Script-Converter-CLI#1]
I do everything that is written and it doesn't work I'll send a photo of the original code and the code that appears converted help please

![● output lua - Visual Studio Code 01_06_2022 14_51_32](https://user-images.githubusercontent.com/81835688/171421594-7ce5e65b-5197-45f5-ba37-ee2373397755.png)
![New Issue · AmpedScripts_Fivem-Script-Converter-CLI - Google Chrome 01_06_2022 14_55_43](https://user-images.githubusercontent.com/81835688/171421920-5760eb0f-13a0-46ec-91c9-8583a1c8b1ce.png)

**Comment by AmpedWasTaken** [comment]
what did you put in the converter?
